site_name: Luck Network Wiki
repo_url: https://github.com/lucknet/luckwiki
nav:
    - Home: 'index.md'
    - Rules: 'rules.md'
site_description: Minecraftサーバー「Luck Network」のWikiページです。
site_author: Luck Network
use_directory_urls: true
copyright: MIT License
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust