site_name: Luck Network Wiki
repo_url: https://github.com/lucknet/luckwiki
site_description: Minecraftサーバー「Luck Network」のWikiページです。
site_author: Luck Network
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust